/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedShiftSettingsRouteImport } from './routes/_authenticated/shift-settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedJobTitlesRouteImport } from './routes/_authenticated/job-titles'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEmployeeOfMonthRouteImport } from './routes/_authenticated/employee-of-month'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company-settings'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBreaksAdminRouteImport } from './routes/_authenticated/breaks-admin'
import { Route as AuthenticatedBreaksRouteImport } from './routes/_authenticated/breaks'
import { Route as AuthenticatedBreakSettingsRouteImport } from './routes/_authenticated/break-settings'
import { Route as AuthenticatedPlatformRouteRouteImport } from './routes/_authenticated/platform/route'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system.settings'
import { Route as AuthenticatedSystemPermissionsRouteImport } from './routes/_authenticated/system.permissions'
import { Route as AuthenticatedSystemBranchesRouteImport } from './routes/_authenticated/system.branches'
import { Route as AuthenticatedSystemBranchManagersRouteImport } from './routes/_authenticated/system.branch-managers'
import { Route as AuthenticatedPlatformOwnersRouteImport } from './routes/_authenticated/platform/owners'
import { Route as ApiPublicHooksGenerateRecurringTasksRouteImport } from './routes/api/public/hooks/generate-recurring-tasks'
import { Route as AuthenticatedPlatformOwnersUserIdRouteImport } from './routes/_authenticated/platform/owners.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftSettingsRoute =
  AuthenticatedShiftSettingsRouteImport.update({
    id: '/shift-settings',
    path: '/shift-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobTitlesRoute = AuthenticatedJobTitlesRouteImport.update({
  id: '/job-titles',
  path: '/job-titles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeOfMonthRoute =
  AuthenticatedEmployeeOfMonthRouteImport.update({
    id: '/employee-of-month',
    path: '/employee-of-month',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksAdminRoute =
  AuthenticatedBreaksAdminRouteImport.update({
    id: '/breaks-admin',
    path: '/breaks-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksRoute = AuthenticatedBreaksRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreakSettingsRoute =
  AuthenticatedBreakSettingsRouteImport.update({
    id: '/break-settings',
    path: '/break-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRouteRoute =
  AuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemPermissionsRoute =
  AuthenticatedSystemPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemBranchesRoute =
  AuthenticatedSystemBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemBranchManagersRoute =
  AuthenticatedSystemBranchManagersRouteImport.update({
    id: '/branch-managers',
    path: '/branch-managers',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedPlatformOwnersRoute =
  AuthenticatedPlatformOwnersRouteImport.update({
    id: '/owners',
    path: '/owners',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const ApiPublicHooksGenerateRecurringTasksRoute =
  ApiPublicHooksGenerateRecurringTasksRouteImport.update({
    id: '/api/public/hooks/generate-recurring-tasks',
    path: '/api/public/hooks/generate-recurring-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlatformOwnersUserIdRoute =
  AuthenticatedPlatformOwnersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedPlatformOwnersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/job-titles': typeof AuthenticatedJobTitlesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/system': typeof AuthenticatedSystemRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/job-titles': typeof AuthenticatedJobTitlesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/system': typeof AuthenticatedSystemRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/_authenticated/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/_authenticated/breaks': typeof AuthenticatedBreaksRoute
  '/_authenticated/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/job-titles': typeof AuthenticatedJobTitlesRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/_authenticated/system': typeof AuthenticatedSystemRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/_authenticated/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/_authenticated/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/_authenticated/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/platform'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/job-titles'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/system'
    | '/tasks'
    | '/platform/owners'
    | '/system/branch-managers'
    | '/system/branches'
    | '/system/permissions'
    | '/system/settings'
    | '/platform/'
    | '/platform/owners/$userId'
    | '/api/public/hooks/generate-recurring-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/job-titles'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/system'
    | '/tasks'
    | '/platform/owners'
    | '/system/branch-managers'
    | '/system/branches'
    | '/system/permissions'
    | '/system/settings'
    | '/platform'
    | '/platform/owners/$userId'
    | '/api/public/hooks/generate-recurring-tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/platform'
    | '/_authenticated/break-settings'
    | '/_authenticated/breaks'
    | '/_authenticated/breaks-admin'
    | '/_authenticated/change-password'
    | '/_authenticated/communications'
    | '/_authenticated/company-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/employee-of-month'
    | '/_authenticated/employees'
    | '/_authenticated/job-titles'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/schedules'
    | '/_authenticated/shift-settings'
    | '/_authenticated/system'
    | '/_authenticated/tasks'
    | '/_authenticated/platform/owners'
    | '/_authenticated/system/branch-managers'
    | '/_authenticated/system/branches'
    | '/_authenticated/system/permissions'
    | '/_authenticated/system/settings'
    | '/_authenticated/platform/'
    | '/_authenticated/platform/owners/$userId'
    | '/api/public/hooks/generate-recurring-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksGenerateRecurringTasksRoute: typeof ApiPublicHooksGenerateRecurringTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift-settings': {
      id: '/_authenticated/shift-settings'
      path: '/shift-settings'
      fullPath: '/shift-settings'
      preLoaderRoute: typeof AuthenticatedShiftSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-titles': {
      id: '/_authenticated/job-titles'
      path: '/job-titles'
      fullPath: '/job-titles'
      preLoaderRoute: typeof AuthenticatedJobTitlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-of-month': {
      id: '/_authenticated/employee-of-month'
      path: '/employee-of-month'
      fullPath: '/employee-of-month'
      preLoaderRoute: typeof AuthenticatedEmployeeOfMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-settings': {
      id: '/_authenticated/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks-admin': {
      id: '/_authenticated/breaks-admin'
      path: '/breaks-admin'
      fullPath: '/breaks-admin'
      preLoaderRoute: typeof AuthenticatedBreaksAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks': {
      id: '/_authenticated/breaks'
      path: '/breaks'
      fullPath: '/breaks'
      preLoaderRoute: typeof AuthenticatedBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/break-settings': {
      id: '/_authenticated/break-settings'
      path: '/break-settings'
      fullPath: '/break-settings'
      preLoaderRoute: typeof AuthenticatedBreakSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/permissions': {
      id: '/_authenticated/system/permissions'
      path: '/permissions'
      fullPath: '/system/permissions'
      preLoaderRoute: typeof AuthenticatedSystemPermissionsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/branches': {
      id: '/_authenticated/system/branches'
      path: '/branches'
      fullPath: '/system/branches'
      preLoaderRoute: typeof AuthenticatedSystemBranchesRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/branch-managers': {
      id: '/_authenticated/system/branch-managers'
      path: '/branch-managers'
      fullPath: '/system/branch-managers'
      preLoaderRoute: typeof AuthenticatedSystemBranchManagersRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/platform/owners': {
      id: '/_authenticated/platform/owners'
      path: '/owners'
      fullPath: '/platform/owners'
      preLoaderRoute: typeof AuthenticatedPlatformOwnersRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/api/public/hooks/generate-recurring-tasks': {
      id: '/api/public/hooks/generate-recurring-tasks'
      path: '/api/public/hooks/generate-recurring-tasks'
      fullPath: '/api/public/hooks/generate-recurring-tasks'
      preLoaderRoute: typeof ApiPublicHooksGenerateRecurringTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/owners/$userId': {
      id: '/_authenticated/platform/owners/$userId'
      path: '/$userId'
      fullPath: '/platform/owners/$userId'
      preLoaderRoute: typeof AuthenticatedPlatformOwnersUserIdRouteImport
      parentRoute: typeof AuthenticatedPlatformOwnersRoute
    }
  }
}

interface AuthenticatedPlatformOwnersRouteChildren {
  AuthenticatedPlatformOwnersUserIdRoute: typeof AuthenticatedPlatformOwnersUserIdRoute
}

const AuthenticatedPlatformOwnersRouteChildren: AuthenticatedPlatformOwnersRouteChildren =
  {
    AuthenticatedPlatformOwnersUserIdRoute:
      AuthenticatedPlatformOwnersUserIdRoute,
  }

const AuthenticatedPlatformOwnersRouteWithChildren =
  AuthenticatedPlatformOwnersRoute._addFileChildren(
    AuthenticatedPlatformOwnersRouteChildren,
  )

interface AuthenticatedPlatformRouteRouteChildren {
  AuthenticatedPlatformOwnersRoute: typeof AuthenticatedPlatformOwnersRouteWithChildren
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteRouteChildren: AuthenticatedPlatformRouteRouteChildren =
  {
    AuthenticatedPlatformOwnersRoute:
      AuthenticatedPlatformOwnersRouteWithChildren,
    AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  }

const AuthenticatedPlatformRouteRouteWithChildren =
  AuthenticatedPlatformRouteRoute._addFileChildren(
    AuthenticatedPlatformRouteRouteChildren,
  )

interface AuthenticatedSystemRouteChildren {
  AuthenticatedSystemBranchManagersRoute: typeof AuthenticatedSystemBranchManagersRoute
  AuthenticatedSystemBranchesRoute: typeof AuthenticatedSystemBranchesRoute
  AuthenticatedSystemPermissionsRoute: typeof AuthenticatedSystemPermissionsRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
}

const AuthenticatedSystemRouteChildren: AuthenticatedSystemRouteChildren = {
  AuthenticatedSystemBranchManagersRoute:
    AuthenticatedSystemBranchManagersRoute,
  AuthenticatedSystemBranchesRoute: AuthenticatedSystemBranchesRoute,
  AuthenticatedSystemPermissionsRoute: AuthenticatedSystemPermissionsRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
}

const AuthenticatedSystemRouteWithChildren =
  AuthenticatedSystemRoute._addFileChildren(AuthenticatedSystemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlatformRouteRoute: typeof AuthenticatedPlatformRouteRouteWithChildren
  AuthenticatedBreakSettingsRoute: typeof AuthenticatedBreakSettingsRoute
  AuthenticatedBreaksRoute: typeof AuthenticatedBreaksRoute
  AuthenticatedBreaksAdminRoute: typeof AuthenticatedBreaksAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeeOfMonthRoute: typeof AuthenticatedEmployeeOfMonthRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedJobTitlesRoute: typeof AuthenticatedJobTitlesRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedShiftSettingsRoute: typeof AuthenticatedShiftSettingsRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlatformRouteRoute: AuthenticatedPlatformRouteRouteWithChildren,
  AuthenticatedBreakSettingsRoute: AuthenticatedBreakSettingsRoute,
  AuthenticatedBreaksRoute: AuthenticatedBreaksRoute,
  AuthenticatedBreaksAdminRoute: AuthenticatedBreaksAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeeOfMonthRoute: AuthenticatedEmployeeOfMonthRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedJobTitlesRoute: AuthenticatedJobTitlesRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedShiftSettingsRoute: AuthenticatedShiftSettingsRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksGenerateRecurringTasksRoute:
    ApiPublicHooksGenerateRecurringTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
