/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPwaManifestRouteImport } from './routes/api/pwa-manifest'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedShiftSettingsRouteImport } from './routes/_authenticated/shift-settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedLeavesAdminRouteImport } from './routes/_authenticated/leaves-admin'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedJobTitlesRouteImport } from './routes/_authenticated/job-titles'
import { Route as AuthenticatedInactiveRouteImport } from './routes/_authenticated/inactive'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEmployeeOfMonthRouteImport } from './routes/_authenticated/employee-of-month'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustodySettingsRouteImport } from './routes/_authenticated/custody-settings'
import { Route as AuthenticatedCustodyLogRouteImport } from './routes/_authenticated/custody-log'
import { Route as AuthenticatedControlLogRouteImport } from './routes/_authenticated/control-log'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company-settings'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBreaksAdminRouteImport } from './routes/_authenticated/breaks-admin'
import { Route as AuthenticatedBreaksRouteImport } from './routes/_authenticated/breaks'
import { Route as AuthenticatedBreakSettingsRouteImport } from './routes/_authenticated/break-settings'
import { Route as AuthenticatedBreakPlanningRouteImport } from './routes/_authenticated/break-planning'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedPlatformRouteRouteImport } from './routes/_authenticated/platform/route'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as ApiPushVapidPublicKeyRouteImport } from './routes/api/push/vapid-public-key'
import { Route as ApiAiChatStreamRouteImport } from './routes/api/ai/chat-stream'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system.settings'
import { Route as AuthenticatedSystemPermissionsRouteImport } from './routes/_authenticated/system.permissions'
import { Route as AuthenticatedSystemBranchesRouteImport } from './routes/_authenticated/system.branches'
import { Route as AuthenticatedSystemBranchManagersRouteImport } from './routes/_authenticated/system.branch-managers'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform/settings'
import { Route as AuthenticatedPlatformRealtimeRouteImport } from './routes/_authenticated/platform/realtime'
import { Route as AuthenticatedPlatformOwnersRouteImport } from './routes/_authenticated/platform/owners'
import { Route as AuthenticatedPlatformNotificationsRouteImport } from './routes/_authenticated/platform/notifications'
import { Route as AuthenticatedPlatformMonitoringRouteImport } from './routes/_authenticated/platform/monitoring'
import { Route as AuthenticatedPlatformFeatureFlagsRouteImport } from './routes/_authenticated/platform/feature-flags'
import { Route as AuthenticatedPlatformControlLogRouteImport } from './routes/_authenticated/platform/control-log'
import { Route as AuthenticatedPlatformCompaniesRouteImport } from './routes/_authenticated/platform/companies'
import { Route as AuthenticatedPlatformBranchesRouteImport } from './routes/_authenticated/platform/branches'
import { Route as AuthenticatedPlatformBillingRouteImport } from './routes/_authenticated/platform/billing'
import { Route as AuthenticatedPlatformAuditLogRouteImport } from './routes/_authenticated/platform/audit-log'
import { Route as AuthenticatedPlatformAnalyticsRouteImport } from './routes/_authenticated/platform/analytics'
import { Route as AuthenticatedPlatformAiRouteImport } from './routes/_authenticated/platform/ai'
import { Route as AuthenticatedPlatformCompaniesIndexRouteImport } from './routes/_authenticated/platform/companies.index'
import { Route as ApiPublicHooksPlatformHealthScanRouteImport } from './routes/api/public/hooks/platform-health-scan'
import { Route as ApiPublicHooksGenerateRecurringTasksRouteImport } from './routes/api/public/hooks/generate-recurring-tasks'
import { Route as ApiPublicHooksDispatchPushRouteImport } from './routes/api/public/hooks/dispatch-push'
import { Route as AuthenticatedPlatformOwnersUserIdRouteImport } from './routes/_authenticated/platform/owners.$userId'
import { Route as AuthenticatedPlatformCompaniesCompanyIdRouteImport } from './routes/_authenticated/platform/companies.$companyId'
import { Route as AuthenticatedPlatformBranchesBranchIdRouteImport } from './routes/_authenticated/platform/branches.$branchId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPwaManifestRoute = ApiPwaManifestRouteImport.update({
  id: '/api/pwa-manifest',
  path: '/api/pwa-manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftSettingsRoute =
  AuthenticatedShiftSettingsRouteImport.update({
    id: '/shift-settings',
    path: '/shift-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeavesAdminRoute =
  AuthenticatedLeavesAdminRouteImport.update({
    id: '/leaves-admin',
    path: '/leaves-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobTitlesRoute = AuthenticatedJobTitlesRouteImport.update({
  id: '/job-titles',
  path: '/job-titles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInactiveRoute = AuthenticatedInactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeOfMonthRoute =
  AuthenticatedEmployeeOfMonthRouteImport.update({
    id: '/employee-of-month',
    path: '/employee-of-month',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustodySettingsRoute =
  AuthenticatedCustodySettingsRouteImport.update({
    id: '/custody-settings',
    path: '/custody-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustodyLogRoute = AuthenticatedCustodyLogRouteImport.update({
  id: '/custody-log',
  path: '/custody-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlLogRoute = AuthenticatedControlLogRouteImport.update({
  id: '/control-log',
  path: '/control-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksAdminRoute =
  AuthenticatedBreaksAdminRouteImport.update({
    id: '/breaks-admin',
    path: '/breaks-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksRoute = AuthenticatedBreaksRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreakSettingsRoute =
  AuthenticatedBreakSettingsRouteImport.update({
    id: '/break-settings',
    path: '/break-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreakPlanningRoute =
  AuthenticatedBreakPlanningRouteImport.update({
    id: '/break-planning',
    path: '/break-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRouteRoute =
  AuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const ApiPushVapidPublicKeyRoute = ApiPushVapidPublicKeyRouteImport.update({
  id: '/api/push/vapid-public-key',
  path: '/api/push/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatStreamRoute = ApiAiChatStreamRouteImport.update({
  id: '/api/ai/chat-stream',
  path: '/api/ai/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemPermissionsRoute =
  AuthenticatedSystemPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemBranchesRoute =
  AuthenticatedSystemBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemBranchManagersRoute =
  AuthenticatedSystemBranchManagersRouteImport.update({
    id: '/branch-managers',
    path: '/branch-managers',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformRealtimeRoute =
  AuthenticatedPlatformRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformOwnersRoute =
  AuthenticatedPlatformOwnersRouteImport.update({
    id: '/owners',
    path: '/owners',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformNotificationsRoute =
  AuthenticatedPlatformNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformMonitoringRoute =
  AuthenticatedPlatformMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformFeatureFlagsRoute =
  AuthenticatedPlatformFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformControlLogRoute =
  AuthenticatedPlatformControlLogRouteImport.update({
    id: '/control-log',
    path: '/control-log',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformCompaniesRoute =
  AuthenticatedPlatformCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformBranchesRoute =
  AuthenticatedPlatformBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformBillingRoute =
  AuthenticatedPlatformBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformAuditLogRoute =
  AuthenticatedPlatformAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformAnalyticsRoute =
  AuthenticatedPlatformAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformAiRoute = AuthenticatedPlatformAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedPlatformRouteRoute,
} as any)
const AuthenticatedPlatformCompaniesIndexRoute =
  AuthenticatedPlatformCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformCompaniesRoute,
  } as any)
const ApiPublicHooksPlatformHealthScanRoute =
  ApiPublicHooksPlatformHealthScanRouteImport.update({
    id: '/api/public/hooks/platform-health-scan',
    path: '/api/public/hooks/platform-health-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateRecurringTasksRoute =
  ApiPublicHooksGenerateRecurringTasksRouteImport.update({
    id: '/api/public/hooks/generate-recurring-tasks',
    path: '/api/public/hooks/generate-recurring-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchPushRoute =
  ApiPublicHooksDispatchPushRouteImport.update({
    id: '/api/public/hooks/dispatch-push',
    path: '/api/public/hooks/dispatch-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlatformOwnersUserIdRoute =
  AuthenticatedPlatformOwnersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedPlatformOwnersRoute,
  } as any)
const AuthenticatedPlatformCompaniesCompanyIdRoute =
  AuthenticatedPlatformCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedPlatformCompaniesRoute,
  } as any)
const AuthenticatedPlatformBranchesBranchIdRoute =
  AuthenticatedPlatformBranchesBranchIdRouteImport.update({
    id: '/$branchId',
    path: '/$branchId',
    getParentRoute: () => AuthenticatedPlatformBranchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/break-planning': typeof AuthenticatedBreakPlanningRoute
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/control-log': typeof AuthenticatedControlLogRoute
  '/custody-log': typeof AuthenticatedCustodyLogRoute
  '/custody-settings': typeof AuthenticatedCustodySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/inactive': typeof AuthenticatedInactiveRoute
  '/job-titles': typeof AuthenticatedJobTitlesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/system': typeof AuthenticatedSystemRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/pwa-manifest': typeof ApiPwaManifestRoute
  '/platform/ai': typeof AuthenticatedPlatformAiRoute
  '/platform/analytics': typeof AuthenticatedPlatformAnalyticsRoute
  '/platform/audit-log': typeof AuthenticatedPlatformAuditLogRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/branches': typeof AuthenticatedPlatformBranchesRouteWithChildren
  '/platform/companies': typeof AuthenticatedPlatformCompaniesRouteWithChildren
  '/platform/control-log': typeof AuthenticatedPlatformControlLogRoute
  '/platform/feature-flags': typeof AuthenticatedPlatformFeatureFlagsRoute
  '/platform/monitoring': typeof AuthenticatedPlatformMonitoringRoute
  '/platform/notifications': typeof AuthenticatedPlatformNotificationsRoute
  '/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/platform/realtime': typeof AuthenticatedPlatformRealtimeRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/api/ai/chat-stream': typeof ApiAiChatStreamRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/platform/branches/$branchId': typeof AuthenticatedPlatformBranchesBranchIdRoute
  '/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
  '/api/public/hooks/platform-health-scan': typeof ApiPublicHooksPlatformHealthScanRoute
  '/platform/companies/': typeof AuthenticatedPlatformCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/break-planning': typeof AuthenticatedBreakPlanningRoute
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/control-log': typeof AuthenticatedControlLogRoute
  '/custody-log': typeof AuthenticatedCustodyLogRoute
  '/custody-settings': typeof AuthenticatedCustodySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/inactive': typeof AuthenticatedInactiveRoute
  '/job-titles': typeof AuthenticatedJobTitlesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/system': typeof AuthenticatedSystemRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/pwa-manifest': typeof ApiPwaManifestRoute
  '/platform/ai': typeof AuthenticatedPlatformAiRoute
  '/platform/analytics': typeof AuthenticatedPlatformAnalyticsRoute
  '/platform/audit-log': typeof AuthenticatedPlatformAuditLogRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/branches': typeof AuthenticatedPlatformBranchesRouteWithChildren
  '/platform/control-log': typeof AuthenticatedPlatformControlLogRoute
  '/platform/feature-flags': typeof AuthenticatedPlatformFeatureFlagsRoute
  '/platform/monitoring': typeof AuthenticatedPlatformMonitoringRoute
  '/platform/notifications': typeof AuthenticatedPlatformNotificationsRoute
  '/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/platform/realtime': typeof AuthenticatedPlatformRealtimeRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/api/ai/chat-stream': typeof ApiAiChatStreamRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/platform/branches/$branchId': typeof AuthenticatedPlatformBranchesBranchIdRoute
  '/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
  '/api/public/hooks/platform-health-scan': typeof ApiPublicHooksPlatformHealthScanRoute
  '/platform/companies': typeof AuthenticatedPlatformCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/break-planning': typeof AuthenticatedBreakPlanningRoute
  '/_authenticated/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/_authenticated/breaks': typeof AuthenticatedBreaksRoute
  '/_authenticated/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/control-log': typeof AuthenticatedControlLogRoute
  '/_authenticated/custody-log': typeof AuthenticatedCustodyLogRoute
  '/_authenticated/custody-settings': typeof AuthenticatedCustodySettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/inactive': typeof AuthenticatedInactiveRoute
  '/_authenticated/job-titles': typeof AuthenticatedJobTitlesRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/leaves-admin': typeof AuthenticatedLeavesAdminRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/_authenticated/system': typeof AuthenticatedSystemRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/pwa-manifest': typeof ApiPwaManifestRoute
  '/_authenticated/platform/ai': typeof AuthenticatedPlatformAiRoute
  '/_authenticated/platform/analytics': typeof AuthenticatedPlatformAnalyticsRoute
  '/_authenticated/platform/audit-log': typeof AuthenticatedPlatformAuditLogRoute
  '/_authenticated/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/_authenticated/platform/branches': typeof AuthenticatedPlatformBranchesRouteWithChildren
  '/_authenticated/platform/companies': typeof AuthenticatedPlatformCompaniesRouteWithChildren
  '/_authenticated/platform/control-log': typeof AuthenticatedPlatformControlLogRoute
  '/_authenticated/platform/feature-flags': typeof AuthenticatedPlatformFeatureFlagsRoute
  '/_authenticated/platform/monitoring': typeof AuthenticatedPlatformMonitoringRoute
  '/_authenticated/platform/notifications': typeof AuthenticatedPlatformNotificationsRoute
  '/_authenticated/platform/owners': typeof AuthenticatedPlatformOwnersRouteWithChildren
  '/_authenticated/platform/realtime': typeof AuthenticatedPlatformRealtimeRoute
  '/_authenticated/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/system/branch-managers': typeof AuthenticatedSystemBranchManagersRoute
  '/_authenticated/system/branches': typeof AuthenticatedSystemBranchesRoute
  '/_authenticated/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/api/ai/chat-stream': typeof ApiAiChatStreamRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/platform/branches/$branchId': typeof AuthenticatedPlatformBranchesBranchIdRoute
  '/_authenticated/platform/companies/$companyId': typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  '/_authenticated/platform/owners/$userId': typeof AuthenticatedPlatformOwnersUserIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
  '/api/public/hooks/platform-health-scan': typeof ApiPublicHooksPlatformHealthScanRoute
  '/_authenticated/platform/companies/': typeof AuthenticatedPlatformCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/platform'
    | '/ai-assistant'
    | '/break-planning'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/control-log'
    | '/custody-log'
    | '/custody-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/inactive'
    | '/job-titles'
    | '/leaves'
    | '/leaves-admin'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/system'
    | '/tasks'
    | '/api/pwa-manifest'
    | '/platform/ai'
    | '/platform/analytics'
    | '/platform/audit-log'
    | '/platform/billing'
    | '/platform/branches'
    | '/platform/companies'
    | '/platform/control-log'
    | '/platform/feature-flags'
    | '/platform/monitoring'
    | '/platform/notifications'
    | '/platform/owners'
    | '/platform/realtime'
    | '/platform/settings'
    | '/system/branch-managers'
    | '/system/branches'
    | '/system/permissions'
    | '/system/settings'
    | '/api/ai/chat-stream'
    | '/api/push/vapid-public-key'
    | '/platform/'
    | '/platform/branches/$branchId'
    | '/platform/companies/$companyId'
    | '/platform/owners/$userId'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/generate-recurring-tasks'
    | '/api/public/hooks/platform-health-scan'
    | '/platform/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/break-planning'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/control-log'
    | '/custody-log'
    | '/custody-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/inactive'
    | '/job-titles'
    | '/leaves'
    | '/leaves-admin'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/system'
    | '/tasks'
    | '/api/pwa-manifest'
    | '/platform/ai'
    | '/platform/analytics'
    | '/platform/audit-log'
    | '/platform/billing'
    | '/platform/branches'
    | '/platform/control-log'
    | '/platform/feature-flags'
    | '/platform/monitoring'
    | '/platform/notifications'
    | '/platform/owners'
    | '/platform/realtime'
    | '/platform/settings'
    | '/system/branch-managers'
    | '/system/branches'
    | '/system/permissions'
    | '/system/settings'
    | '/api/ai/chat-stream'
    | '/api/push/vapid-public-key'
    | '/platform'
    | '/platform/branches/$branchId'
    | '/platform/companies/$companyId'
    | '/platform/owners/$userId'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/generate-recurring-tasks'
    | '/api/public/hooks/platform-health-scan'
    | '/platform/companies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/platform'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/break-planning'
    | '/_authenticated/break-settings'
    | '/_authenticated/breaks'
    | '/_authenticated/breaks-admin'
    | '/_authenticated/change-password'
    | '/_authenticated/communications'
    | '/_authenticated/company-settings'
    | '/_authenticated/control-log'
    | '/_authenticated/custody-log'
    | '/_authenticated/custody-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/employee-of-month'
    | '/_authenticated/employees'
    | '/_authenticated/inactive'
    | '/_authenticated/job-titles'
    | '/_authenticated/leaves'
    | '/_authenticated/leaves-admin'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/schedules'
    | '/_authenticated/shift-settings'
    | '/_authenticated/system'
    | '/_authenticated/tasks'
    | '/api/pwa-manifest'
    | '/_authenticated/platform/ai'
    | '/_authenticated/platform/analytics'
    | '/_authenticated/platform/audit-log'
    | '/_authenticated/platform/billing'
    | '/_authenticated/platform/branches'
    | '/_authenticated/platform/companies'
    | '/_authenticated/platform/control-log'
    | '/_authenticated/platform/feature-flags'
    | '/_authenticated/platform/monitoring'
    | '/_authenticated/platform/notifications'
    | '/_authenticated/platform/owners'
    | '/_authenticated/platform/realtime'
    | '/_authenticated/platform/settings'
    | '/_authenticated/system/branch-managers'
    | '/_authenticated/system/branches'
    | '/_authenticated/system/permissions'
    | '/_authenticated/system/settings'
    | '/api/ai/chat-stream'
    | '/api/push/vapid-public-key'
    | '/_authenticated/platform/'
    | '/_authenticated/platform/branches/$branchId'
    | '/_authenticated/platform/companies/$companyId'
    | '/_authenticated/platform/owners/$userId'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/generate-recurring-tasks'
    | '/api/public/hooks/platform-health-scan'
    | '/_authenticated/platform/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPwaManifestRoute: typeof ApiPwaManifestRoute
  ApiAiChatStreamRoute: typeof ApiAiChatStreamRoute
  ApiPushVapidPublicKeyRoute: typeof ApiPushVapidPublicKeyRoute
  ApiPublicHooksDispatchPushRoute: typeof ApiPublicHooksDispatchPushRoute
  ApiPublicHooksGenerateRecurringTasksRoute: typeof ApiPublicHooksGenerateRecurringTasksRoute
  ApiPublicHooksPlatformHealthScanRoute: typeof ApiPublicHooksPlatformHealthScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pwa-manifest': {
      id: '/api/pwa-manifest'
      path: '/api/pwa-manifest'
      fullPath: '/api/pwa-manifest'
      preLoaderRoute: typeof ApiPwaManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift-settings': {
      id: '/_authenticated/shift-settings'
      path: '/shift-settings'
      fullPath: '/shift-settings'
      preLoaderRoute: typeof AuthenticatedShiftSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves-admin': {
      id: '/_authenticated/leaves-admin'
      path: '/leaves-admin'
      fullPath: '/leaves-admin'
      preLoaderRoute: typeof AuthenticatedLeavesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-titles': {
      id: '/_authenticated/job-titles'
      path: '/job-titles'
      fullPath: '/job-titles'
      preLoaderRoute: typeof AuthenticatedJobTitlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inactive': {
      id: '/_authenticated/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof AuthenticatedInactiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-of-month': {
      id: '/_authenticated/employee-of-month'
      path: '/employee-of-month'
      fullPath: '/employee-of-month'
      preLoaderRoute: typeof AuthenticatedEmployeeOfMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custody-settings': {
      id: '/_authenticated/custody-settings'
      path: '/custody-settings'
      fullPath: '/custody-settings'
      preLoaderRoute: typeof AuthenticatedCustodySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custody-log': {
      id: '/_authenticated/custody-log'
      path: '/custody-log'
      fullPath: '/custody-log'
      preLoaderRoute: typeof AuthenticatedCustodyLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-log': {
      id: '/_authenticated/control-log'
      path: '/control-log'
      fullPath: '/control-log'
      preLoaderRoute: typeof AuthenticatedControlLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-settings': {
      id: '/_authenticated/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks-admin': {
      id: '/_authenticated/breaks-admin'
      path: '/breaks-admin'
      fullPath: '/breaks-admin'
      preLoaderRoute: typeof AuthenticatedBreaksAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks': {
      id: '/_authenticated/breaks'
      path: '/breaks'
      fullPath: '/breaks'
      preLoaderRoute: typeof AuthenticatedBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/break-settings': {
      id: '/_authenticated/break-settings'
      path: '/break-settings'
      fullPath: '/break-settings'
      preLoaderRoute: typeof AuthenticatedBreakSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/break-planning': {
      id: '/_authenticated/break-planning'
      path: '/break-planning'
      fullPath: '/break-planning'
      preLoaderRoute: typeof AuthenticatedBreakPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/api/push/vapid-public-key': {
      id: '/api/push/vapid-public-key'
      path: '/api/push/vapid-public-key'
      fullPath: '/api/push/vapid-public-key'
      preLoaderRoute: typeof ApiPushVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-stream': {
      id: '/api/ai/chat-stream'
      path: '/api/ai/chat-stream'
      fullPath: '/api/ai/chat-stream'
      preLoaderRoute: typeof ApiAiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/permissions': {
      id: '/_authenticated/system/permissions'
      path: '/permissions'
      fullPath: '/system/permissions'
      preLoaderRoute: typeof AuthenticatedSystemPermissionsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/branches': {
      id: '/_authenticated/system/branches'
      path: '/branches'
      fullPath: '/system/branches'
      preLoaderRoute: typeof AuthenticatedSystemBranchesRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/branch-managers': {
      id: '/_authenticated/system/branch-managers'
      path: '/branch-managers'
      fullPath: '/system/branch-managers'
      preLoaderRoute: typeof AuthenticatedSystemBranchManagersRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/platform/settings': {
      id: '/_authenticated/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/realtime': {
      id: '/_authenticated/platform/realtime'
      path: '/realtime'
      fullPath: '/platform/realtime'
      preLoaderRoute: typeof AuthenticatedPlatformRealtimeRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/owners': {
      id: '/_authenticated/platform/owners'
      path: '/owners'
      fullPath: '/platform/owners'
      preLoaderRoute: typeof AuthenticatedPlatformOwnersRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/notifications': {
      id: '/_authenticated/platform/notifications'
      path: '/notifications'
      fullPath: '/platform/notifications'
      preLoaderRoute: typeof AuthenticatedPlatformNotificationsRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/monitoring': {
      id: '/_authenticated/platform/monitoring'
      path: '/monitoring'
      fullPath: '/platform/monitoring'
      preLoaderRoute: typeof AuthenticatedPlatformMonitoringRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/feature-flags': {
      id: '/_authenticated/platform/feature-flags'
      path: '/feature-flags'
      fullPath: '/platform/feature-flags'
      preLoaderRoute: typeof AuthenticatedPlatformFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/control-log': {
      id: '/_authenticated/platform/control-log'
      path: '/control-log'
      fullPath: '/platform/control-log'
      preLoaderRoute: typeof AuthenticatedPlatformControlLogRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/companies': {
      id: '/_authenticated/platform/companies'
      path: '/companies'
      fullPath: '/platform/companies'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/branches': {
      id: '/_authenticated/platform/branches'
      path: '/branches'
      fullPath: '/platform/branches'
      preLoaderRoute: typeof AuthenticatedPlatformBranchesRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/billing': {
      id: '/_authenticated/platform/billing'
      path: '/billing'
      fullPath: '/platform/billing'
      preLoaderRoute: typeof AuthenticatedPlatformBillingRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/audit-log': {
      id: '/_authenticated/platform/audit-log'
      path: '/audit-log'
      fullPath: '/platform/audit-log'
      preLoaderRoute: typeof AuthenticatedPlatformAuditLogRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/analytics': {
      id: '/_authenticated/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof AuthenticatedPlatformAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/ai': {
      id: '/_authenticated/platform/ai'
      path: '/ai'
      fullPath: '/platform/ai'
      preLoaderRoute: typeof AuthenticatedPlatformAiRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/companies/': {
      id: '/_authenticated/platform/companies/'
      path: '/'
      fullPath: '/platform/companies/'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformCompaniesRoute
    }
    '/api/public/hooks/platform-health-scan': {
      id: '/api/public/hooks/platform-health-scan'
      path: '/api/public/hooks/platform-health-scan'
      fullPath: '/api/public/hooks/platform-health-scan'
      preLoaderRoute: typeof ApiPublicHooksPlatformHealthScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-recurring-tasks': {
      id: '/api/public/hooks/generate-recurring-tasks'
      path: '/api/public/hooks/generate-recurring-tasks'
      fullPath: '/api/public/hooks/generate-recurring-tasks'
      preLoaderRoute: typeof ApiPublicHooksGenerateRecurringTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-push': {
      id: '/api/public/hooks/dispatch-push'
      path: '/api/public/hooks/dispatch-push'
      fullPath: '/api/public/hooks/dispatch-push'
      preLoaderRoute: typeof ApiPublicHooksDispatchPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/owners/$userId': {
      id: '/_authenticated/platform/owners/$userId'
      path: '/$userId'
      fullPath: '/platform/owners/$userId'
      preLoaderRoute: typeof AuthenticatedPlatformOwnersUserIdRouteImport
      parentRoute: typeof AuthenticatedPlatformOwnersRoute
    }
    '/_authenticated/platform/companies/$companyId': {
      id: '/_authenticated/platform/companies/$companyId'
      path: '/$companyId'
      fullPath: '/platform/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedPlatformCompaniesRoute
    }
    '/_authenticated/platform/branches/$branchId': {
      id: '/_authenticated/platform/branches/$branchId'
      path: '/$branchId'
      fullPath: '/platform/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedPlatformBranchesBranchIdRouteImport
      parentRoute: typeof AuthenticatedPlatformBranchesRoute
    }
  }
}

interface AuthenticatedPlatformBranchesRouteChildren {
  AuthenticatedPlatformBranchesBranchIdRoute: typeof AuthenticatedPlatformBranchesBranchIdRoute
}

const AuthenticatedPlatformBranchesRouteChildren: AuthenticatedPlatformBranchesRouteChildren =
  {
    AuthenticatedPlatformBranchesBranchIdRoute:
      AuthenticatedPlatformBranchesBranchIdRoute,
  }

const AuthenticatedPlatformBranchesRouteWithChildren =
  AuthenticatedPlatformBranchesRoute._addFileChildren(
    AuthenticatedPlatformBranchesRouteChildren,
  )

interface AuthenticatedPlatformCompaniesRouteChildren {
  AuthenticatedPlatformCompaniesCompanyIdRoute: typeof AuthenticatedPlatformCompaniesCompanyIdRoute
  AuthenticatedPlatformCompaniesIndexRoute: typeof AuthenticatedPlatformCompaniesIndexRoute
}

const AuthenticatedPlatformCompaniesRouteChildren: AuthenticatedPlatformCompaniesRouteChildren =
  {
    AuthenticatedPlatformCompaniesCompanyIdRoute:
      AuthenticatedPlatformCompaniesCompanyIdRoute,
    AuthenticatedPlatformCompaniesIndexRoute:
      AuthenticatedPlatformCompaniesIndexRoute,
  }

const AuthenticatedPlatformCompaniesRouteWithChildren =
  AuthenticatedPlatformCompaniesRoute._addFileChildren(
    AuthenticatedPlatformCompaniesRouteChildren,
  )

interface AuthenticatedPlatformOwnersRouteChildren {
  AuthenticatedPlatformOwnersUserIdRoute: typeof AuthenticatedPlatformOwnersUserIdRoute
}

const AuthenticatedPlatformOwnersRouteChildren: AuthenticatedPlatformOwnersRouteChildren =
  {
    AuthenticatedPlatformOwnersUserIdRoute:
      AuthenticatedPlatformOwnersUserIdRoute,
  }

const AuthenticatedPlatformOwnersRouteWithChildren =
  AuthenticatedPlatformOwnersRoute._addFileChildren(
    AuthenticatedPlatformOwnersRouteChildren,
  )

interface AuthenticatedPlatformRouteRouteChildren {
  AuthenticatedPlatformAiRoute: typeof AuthenticatedPlatformAiRoute
  AuthenticatedPlatformAnalyticsRoute: typeof AuthenticatedPlatformAnalyticsRoute
  AuthenticatedPlatformAuditLogRoute: typeof AuthenticatedPlatformAuditLogRoute
  AuthenticatedPlatformBillingRoute: typeof AuthenticatedPlatformBillingRoute
  AuthenticatedPlatformBranchesRoute: typeof AuthenticatedPlatformBranchesRouteWithChildren
  AuthenticatedPlatformCompaniesRoute: typeof AuthenticatedPlatformCompaniesRouteWithChildren
  AuthenticatedPlatformControlLogRoute: typeof AuthenticatedPlatformControlLogRoute
  AuthenticatedPlatformFeatureFlagsRoute: typeof AuthenticatedPlatformFeatureFlagsRoute
  AuthenticatedPlatformMonitoringRoute: typeof AuthenticatedPlatformMonitoringRoute
  AuthenticatedPlatformNotificationsRoute: typeof AuthenticatedPlatformNotificationsRoute
  AuthenticatedPlatformOwnersRoute: typeof AuthenticatedPlatformOwnersRouteWithChildren
  AuthenticatedPlatformRealtimeRoute: typeof AuthenticatedPlatformRealtimeRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteRouteChildren: AuthenticatedPlatformRouteRouteChildren =
  {
    AuthenticatedPlatformAiRoute: AuthenticatedPlatformAiRoute,
    AuthenticatedPlatformAnalyticsRoute: AuthenticatedPlatformAnalyticsRoute,
    AuthenticatedPlatformAuditLogRoute: AuthenticatedPlatformAuditLogRoute,
    AuthenticatedPlatformBillingRoute: AuthenticatedPlatformBillingRoute,
    AuthenticatedPlatformBranchesRoute:
      AuthenticatedPlatformBranchesRouteWithChildren,
    AuthenticatedPlatformCompaniesRoute:
      AuthenticatedPlatformCompaniesRouteWithChildren,
    AuthenticatedPlatformControlLogRoute: AuthenticatedPlatformControlLogRoute,
    AuthenticatedPlatformFeatureFlagsRoute:
      AuthenticatedPlatformFeatureFlagsRoute,
    AuthenticatedPlatformMonitoringRoute: AuthenticatedPlatformMonitoringRoute,
    AuthenticatedPlatformNotificationsRoute:
      AuthenticatedPlatformNotificationsRoute,
    AuthenticatedPlatformOwnersRoute:
      AuthenticatedPlatformOwnersRouteWithChildren,
    AuthenticatedPlatformRealtimeRoute: AuthenticatedPlatformRealtimeRoute,
    AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
    AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  }

const AuthenticatedPlatformRouteRouteWithChildren =
  AuthenticatedPlatformRouteRoute._addFileChildren(
    AuthenticatedPlatformRouteRouteChildren,
  )

interface AuthenticatedSystemRouteChildren {
  AuthenticatedSystemBranchManagersRoute: typeof AuthenticatedSystemBranchManagersRoute
  AuthenticatedSystemBranchesRoute: typeof AuthenticatedSystemBranchesRoute
  AuthenticatedSystemPermissionsRoute: typeof AuthenticatedSystemPermissionsRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
}

const AuthenticatedSystemRouteChildren: AuthenticatedSystemRouteChildren = {
  AuthenticatedSystemBranchManagersRoute:
    AuthenticatedSystemBranchManagersRoute,
  AuthenticatedSystemBranchesRoute: AuthenticatedSystemBranchesRoute,
  AuthenticatedSystemPermissionsRoute: AuthenticatedSystemPermissionsRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
}

const AuthenticatedSystemRouteWithChildren =
  AuthenticatedSystemRoute._addFileChildren(AuthenticatedSystemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlatformRouteRoute: typeof AuthenticatedPlatformRouteRouteWithChildren
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedBreakPlanningRoute: typeof AuthenticatedBreakPlanningRoute
  AuthenticatedBreakSettingsRoute: typeof AuthenticatedBreakSettingsRoute
  AuthenticatedBreaksRoute: typeof AuthenticatedBreaksRoute
  AuthenticatedBreaksAdminRoute: typeof AuthenticatedBreaksAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedControlLogRoute: typeof AuthenticatedControlLogRoute
  AuthenticatedCustodyLogRoute: typeof AuthenticatedCustodyLogRoute
  AuthenticatedCustodySettingsRoute: typeof AuthenticatedCustodySettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeeOfMonthRoute: typeof AuthenticatedEmployeeOfMonthRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInactiveRoute: typeof AuthenticatedInactiveRoute
  AuthenticatedJobTitlesRoute: typeof AuthenticatedJobTitlesRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedLeavesAdminRoute: typeof AuthenticatedLeavesAdminRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedShiftSettingsRoute: typeof AuthenticatedShiftSettingsRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlatformRouteRoute: AuthenticatedPlatformRouteRouteWithChildren,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedBreakPlanningRoute: AuthenticatedBreakPlanningRoute,
  AuthenticatedBreakSettingsRoute: AuthenticatedBreakSettingsRoute,
  AuthenticatedBreaksRoute: AuthenticatedBreaksRoute,
  AuthenticatedBreaksAdminRoute: AuthenticatedBreaksAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedControlLogRoute: AuthenticatedControlLogRoute,
  AuthenticatedCustodyLogRoute: AuthenticatedCustodyLogRoute,
  AuthenticatedCustodySettingsRoute: AuthenticatedCustodySettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeeOfMonthRoute: AuthenticatedEmployeeOfMonthRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInactiveRoute: AuthenticatedInactiveRoute,
  AuthenticatedJobTitlesRoute: AuthenticatedJobTitlesRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedLeavesAdminRoute: AuthenticatedLeavesAdminRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedShiftSettingsRoute: AuthenticatedShiftSettingsRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPwaManifestRoute: ApiPwaManifestRoute,
  ApiAiChatStreamRoute: ApiAiChatStreamRoute,
  ApiPushVapidPublicKeyRoute: ApiPushVapidPublicKeyRoute,
  ApiPublicHooksDispatchPushRoute: ApiPublicHooksDispatchPushRoute,
  ApiPublicHooksGenerateRecurringTasksRoute:
    ApiPublicHooksGenerateRecurringTasksRoute,
  ApiPublicHooksPlatformHealthScanRoute: ApiPublicHooksPlatformHealthScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
