/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedShiftSettingsRouteImport } from './routes/_authenticated/shift-settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEmployeeOfMonthRouteImport } from './routes/_authenticated/employee-of-month'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company-settings'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBreaksAdminRouteImport } from './routes/_authenticated/breaks-admin'
import { Route as AuthenticatedBreaksRouteImport } from './routes/_authenticated/breaks'
import { Route as AuthenticatedBreakSettingsRouteImport } from './routes/_authenticated/break-settings'
import { Route as ApiPublicHooksGenerateRecurringTasksRouteImport } from './routes/api/public/hooks/generate-recurring-tasks'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftSettingsRoute =
  AuthenticatedShiftSettingsRouteImport.update({
    id: '/shift-settings',
    path: '/shift-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeOfMonthRoute =
  AuthenticatedEmployeeOfMonthRouteImport.update({
    id: '/employee-of-month',
    path: '/employee-of-month',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksAdminRoute =
  AuthenticatedBreaksAdminRouteImport.update({
    id: '/breaks-admin',
    path: '/breaks-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksRoute = AuthenticatedBreaksRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreakSettingsRoute =
  AuthenticatedBreakSettingsRouteImport.update({
    id: '/break-settings',
    path: '/break-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateRecurringTasksRoute =
  ApiPublicHooksGenerateRecurringTasksRouteImport.update({
    id: '/api/public/hooks/generate-recurring-tasks',
    path: '/api/public/hooks/generate-recurring-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/break-settings': typeof AuthenticatedBreakSettingsRoute
  '/_authenticated/breaks': typeof AuthenticatedBreaksRoute
  '/_authenticated/breaks-admin': typeof AuthenticatedBreaksAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employee-of-month': typeof AuthenticatedEmployeeOfMonthRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/shift-settings': typeof AuthenticatedShiftSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/public/hooks/generate-recurring-tasks': typeof ApiPublicHooksGenerateRecurringTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/tasks'
    | '/api/public/hooks/generate-recurring-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/break-settings'
    | '/breaks'
    | '/breaks-admin'
    | '/change-password'
    | '/communications'
    | '/company-settings'
    | '/dashboard'
    | '/departments'
    | '/employee-of-month'
    | '/employees'
    | '/permissions'
    | '/profile'
    | '/schedules'
    | '/shift-settings'
    | '/tasks'
    | '/api/public/hooks/generate-recurring-tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/break-settings'
    | '/_authenticated/breaks'
    | '/_authenticated/breaks-admin'
    | '/_authenticated/change-password'
    | '/_authenticated/communications'
    | '/_authenticated/company-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/employee-of-month'
    | '/_authenticated/employees'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/schedules'
    | '/_authenticated/shift-settings'
    | '/_authenticated/tasks'
    | '/api/public/hooks/generate-recurring-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksGenerateRecurringTasksRoute: typeof ApiPublicHooksGenerateRecurringTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift-settings': {
      id: '/_authenticated/shift-settings'
      path: '/shift-settings'
      fullPath: '/shift-settings'
      preLoaderRoute: typeof AuthenticatedShiftSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-of-month': {
      id: '/_authenticated/employee-of-month'
      path: '/employee-of-month'
      fullPath: '/employee-of-month'
      preLoaderRoute: typeof AuthenticatedEmployeeOfMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-settings': {
      id: '/_authenticated/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks-admin': {
      id: '/_authenticated/breaks-admin'
      path: '/breaks-admin'
      fullPath: '/breaks-admin'
      preLoaderRoute: typeof AuthenticatedBreaksAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks': {
      id: '/_authenticated/breaks'
      path: '/breaks'
      fullPath: '/breaks'
      preLoaderRoute: typeof AuthenticatedBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/break-settings': {
      id: '/_authenticated/break-settings'
      path: '/break-settings'
      fullPath: '/break-settings'
      preLoaderRoute: typeof AuthenticatedBreakSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-recurring-tasks': {
      id: '/api/public/hooks/generate-recurring-tasks'
      path: '/api/public/hooks/generate-recurring-tasks'
      fullPath: '/api/public/hooks/generate-recurring-tasks'
      preLoaderRoute: typeof ApiPublicHooksGenerateRecurringTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBreakSettingsRoute: typeof AuthenticatedBreakSettingsRoute
  AuthenticatedBreaksRoute: typeof AuthenticatedBreaksRoute
  AuthenticatedBreaksAdminRoute: typeof AuthenticatedBreaksAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeeOfMonthRoute: typeof AuthenticatedEmployeeOfMonthRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedShiftSettingsRoute: typeof AuthenticatedShiftSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBreakSettingsRoute: AuthenticatedBreakSettingsRoute,
  AuthenticatedBreaksRoute: AuthenticatedBreaksRoute,
  AuthenticatedBreaksAdminRoute: AuthenticatedBreaksAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeeOfMonthRoute: AuthenticatedEmployeeOfMonthRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedShiftSettingsRoute: AuthenticatedShiftSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksGenerateRecurringTasksRoute:
    ApiPublicHooksGenerateRecurringTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
